### ISSUE TITLE
Suggestion for better API consumption

### ISSUE THREAD

**Issue by RaphaelDDL** [QuazzyWazzy/e7-gacha-simulator#1]
Hi there,

Cool tool, good job. I was checking the source and I see you were thinking in caching each API call (it's commented out for now).

A better suggestion: When someone enters the page, you can call instead `api/hero` and `/api/artifact` and save those in memory (aka js variable).

This way, during that same session (until user refreshes the page), you won't need to call API as you have data for all Heroes and Artifacts.

I say just because there's a limit of calls from same IP per minute (so app doesn't suffer ddos). Therefore people clicking summon non-stop might end up getting error when summoning or when clicking on the hero to see it's details on the E7DB website itself, for the next minute.

Let me know what you think :)

Best,
Raphael

Edit: Here what I mean (yes, I return 418, lol):
![image](https://user-images.githubusercontent.com/1087109/53295210-45caef80-37d5-11e9-84a0-79a6eaa0b6f6.png)

**Comment by RainAfterDark** [comment]
Yeah I originally planned on caching unit info as they got requested but there was a weird bug and so I've commented it out for now. I'll find a way to make it work. Thanks for the heads-up.

**Comment by RainAfterDark** [comment]
Ok, so I went with your idea. Now it only sends a request at page startup and gets all the info required from there. Summoning should be significantly faster now (and spammable without limits lol). Though startup might take a little bit more time.

I've managed to fix the weird bug regarding the previous method. Turns out when getUnitInfo() is called and the unit is already in cache it goes directly to summonUnit(), and by that time selecting the summon card using jQuery's selector returns nothing (since the card doesn't exist yet? But it's already there. Not very sure why that happens). I fixed it by making a reference to the card on Roll() which would then be used by summonUnit() later on instead of directly selecting it.

Ty for issuing, case is closed now.
